"""add_webhook_channels_table

Revision ID: add_webhook_channels
Revises: edd6fcefb3d1
Create Date: 2025-08-13 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import DateTime


# revision identifiers, used by Alembic.
revision = 'add_webhook_channels'
down_revision = 'edd6fcefb3d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_channels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('channel_id', sa.String(length=255), nullable=False),
        sa.Column('resource_id', sa.String(length=255), nullable=False),
        sa.Column('folder_id', sa.String(length=255), nullable=False),
        sa.Column('webhook_url', sa.Text(), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('expiration', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', DateTime(), nullable=False),
        sa.Column('updated_at', DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_channels_channel_id'), 'webhook_channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_webhook_channels_folder_id'), 'webhook_channels', ['folder_id'], unique=False)
    op.create_index(op.f('ix_webhook_channels_id'), 'webhook_channels', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_channels_status'), 'webhook_channels', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_channels_status'), table_name='webhook_channels')
    op.drop_index(op.f('ix_webhook_channels_id'), table_name='webhook_channels')
    op.drop_index(op.f('ix_webhook_channels_folder_id'), table_name='webhook_channels')
    op.drop_index(op.f('ix_webhook_channels_channel_id'), table_name='webhook_channels')
    op.drop_table('webhook_channels')
    # ### end Alembic commands ###
